[tool.poetry]
name = "ai-chatbot"
version = "0.1.0"
description = ""
authors = ["Bogdan <bogdanatrosenko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
setuptools = "^75.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
